import {
  Baby,
  Brain,
  Briefcase,
  Coffee,
  Expand,
  Eye,
  Heading,
  Lightbulb,
  List,
  Megaphone,
  Paintbrush,
  Pen,
  Play,
  Plus,
  Quote,
  Scale,
  Scissors,
  Settings2,
  Shrink,
  Sparkle,
  SpellCheck,
  Star,
} from 'lucide-react'

export const aiCommandOptions = [
  {
    group: 'Rewrite',
    description: 'These commands will **replace** your selected text.',
    options: [
      { label: 'Rephrase', value: 'Rephrase the text for clarity and natural flow.', icon: Brain, replaceSelected: true },
      { label: 'Fix grammar & spelling', value: 'Correct any grammar, spelling, or punctuation errors in the text.', icon: SpellCheck, replaceSelected: true },
      { label: 'Simplify language', value: 'Rewrite the text in simpler language while preserving the meaning.', icon: Pen, replaceSelected: true },
      { label: 'Change tone', value: 'Rewrite the text with a different tone.', icon: Settings2, replaceSelected: true },
      { label: 'Change point of view', value: 'Rewrite the text from a different point of view.', icon: Eye, replaceSelected: true },
      { label: 'Make more formal', value: 'Rewrite the text to be more formal.', icon: Briefcase, replaceSelected: true },
      { label: 'Make more casual', value: 'Rewrite the text to be more casual.', icon: Coffee, replaceSelected: true },
    ],
  },
  {
    group: 'Summarise & Expand',
    description: 'These commands will **replace** your selected text.',
    options: [
      { label: 'Summarise', value: 'Summarise the text concisely.', icon: Pen, replaceSelected: true },
      { label: 'Make longer', value: 'Expand on the text and add more detail.', icon: Expand, replaceSelected: true },
      { label: 'Make shorter', value: 'Shorten the text by removing unnecessary detail.', icon: Scissors, replaceSelected: true },
      { label: 'Bullet point summary', value: 'Summarise the text as bullet points.', icon: List, replaceSelected: true },
      { label: 'Highlight key points', value: 'Highlight the key points in the text.', icon: Star, replaceSelected: true },
      { label: "Explain like I'm 5", value: 'Rewrite the text for a 5-year-old.', icon: Baby, replaceSelected: true },
    ],
  },
  {
    group: 'Generate / Insert',
    description: 'These commands will **insert** new content.',
    options: [
      { label: 'Continue writing', value: 'Continue writing from where the text ends.', icon: Play, replaceSelected: false },
      { label: 'Add a quote', value: 'Add a relevant quote.', icon: Quote, replaceSelected: false },
      { label: 'Add heading', value: 'Add a heading above this text.', icon: Heading, replaceSelected: false },
      { label: 'List ideas', value: 'List several ideas based on the text.', icon: List, replaceSelected: false },
      { label: 'Generate example', value: 'Add a practical example.', icon: Lightbulb, replaceSelected: false },
      { label: 'Add counterpoint', value: 'Add an alternative perspective.', icon: Scale, replaceSelected: false },
    ],
  },
  {
    group: 'Style',
    description: 'These commands will **replace** your selected text.',
    options: [
      { label: 'Make persuasive', value: 'Rewrite to be more persuasive.', icon: Megaphone, replaceSelected: true },
      { label: 'Make descriptive', value: 'Rewrite with vivid descriptions.', icon: Paintbrush, replaceSelected: true },
      { label: 'Make concise', value: 'Make the text more concise.', icon: Shrink, replaceSelected: true },
      { label: 'Make engaging', value: 'Rewrite to be more engaging.', icon: Sparkle, replaceSelected: true },
    ],
  },
]
